### PR TITLE
Update README to provide details on how to run this, and also a slightly more viable alternative.

### PR DESCRIPTION
**Pull request by dxf**

### CODE REVIEW

**Review by isamrish — COMMENTED** [review]
@dxf can you please remove last line which is related to cloudflare...

**Comment by dxf** [comment]
ofc @IsAmrish

**Comment by dxf** [comment]
done!

**Review by isamrish — APPROVED** [review]
looks good to me

**Comment by isamrish** [comment]
Hi @dxf  Thank you very much for participating in Hacktoberfest and contributing to OpenEBS and in general to the Open Source. If you have not already starred/liked the following repositories,  you may want to do so now :slightly_smiling_face:

[OpenEBS](https://github.com/openebs/openebs/stargazers) [Maya](https://github.com/openebs/maya/stargazers) [Litmus](https://github.com/openebs/litmus/stargazers) [NDM](https://github.com/openebs/node-disk-manager/stargazers) [WeaveScope](https://github.com/weaveworks/scope/stargazers) [LongHorn](https://github.com/openebs/longhorn/stargazers) [HeptioArk](https://github.com/heptio/ark/stargazers)

**Comment by dxf** [comment]
Thank you! Have I become eligible for the OpenEBS shirt? My email is me@daf.lol if you need it. (It says on your site that OpenEBS will email me, but I don't know how you'll get my email haha

**Comment by dxf** [comment]
Bumping this. I never seem to have got an email or anything?

**Comment by NisantaSahoo** [comment]
Hello @dxf, unfortunately there might be some kind of error for which the mail was not sent. Can you please check now

**Comment by dxf** [comment]
Got it! Thanks muchly

**Pull request merged**
